# Generated by Django 3.0.6 on 2020-05-15 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partidas', models.IntegerField()),
                ('total_turnos', models.IntegerField()),
                ('media_turnos', models.IntegerField()),
                ('vencedor', models.CharField(max_length=50)),
                ('timeout', models.IntegerField()),
                ('aleatorio', models.FloatField()),
                ('cauteloso', models.FloatField()),
                ('exigente', models.FloatField()),
                ('impulsivo', models.FloatField()),
            ],
            options={
                'verbose_name': 'jogo',
                'verbose_name_plural': 'jogos',
            },
        ),
    ]
